### ISSUE TITLE
Fail CI if `sbt tut` hasn't been re-run?

### ISSUE THREAD

**Issue by avi-stripe** [stripe/rainier#110]
In theory the nice thing about `tut` docs is that if they get out of sync with the actual API, they will fail to compile. But in practice that only helps if you remember to re-generate them after every change. Could we somehow have travis fail if the tut output isn't newer than every source file (or every source file in rainierCore, or something)?

cc @travisbrown-stripe

**Comment by andyscott** [comment]
This is pretty easy to turn on-- I have a local branch with it already set up! The problem is that a variety of the generate outputs aren't deterministic. I've been able to fix most of them except the plots. Per our previous conversation on this, it's likely due to non deterministic IR generated code yielding different commutative operation order for floating point operations that aren't actually commutative.
