### ISSUE TITLE
How to re-use a fitted model in the updated tour.md docs?

### ISSUE THREAD

**Issue by espears4sq** [stripe/rainier#181]
A [recent commit](https://github.com/stripe/rainier/commit/bcfa856ed2abcb760f6b5ddb2d10e63d4dab27f8) changed the `tour.md` example from yielding plain `regression` to instead yield a specific prediction, `regression.predict(21)`. If just yielding `regression`, then `model.sample` gives an error for not finding an implicit value for parameter sampleable.

How do we re-use models in this case and generate predictions for different inputs after model fitting? The doc makes it seem that you must re-run the `for` expression for each such time.

**Comment by mio-stripe** [comment]
👋 @espears4sq good question! If you just yield the `regression` 
```
val model = for {
    slope <- LogNormal(0,1).param
    intercept <- LogNormal(0,1).param
    regression <- Predictor.from{x: Int => Poisson(x*slope + intercept)}.fit(data)
} yield regression
```

then what you get is a `RandomVariable[Predictor[Int, Int, Poisson]]`. If you then `model.map(_.predict(21)` you get back what is in `tour.md`

```
val tourModel = for {
    slope <- LogNormal(0,1).param
    intercept <- LogNormal(0,1).param
    regression <- Predictor.from{x: Int => Poisson(x*slope + intercept)}.fit(data)
} yield regression.predict(21)
```

which is a `RandomVariable[Generator[Int]]`. This is something you can `.sample()` to generate predictions for the input of `21.`.

So the general answer is: take `model` which just yields a `regression` and, to generate predictions for `n`, do
```model.map(_.predict(n)).sample()```

Does that help?

**Comment by mio-stripe** [comment]
Another answer which may be more what you were getting at is: you can also fit a model, record it, then replay it later. As before, we might have
```
val observations =  List((0,8), (1,12), (2,16), (3,20), (4,21), (5,31), (6,23), (7,33), (8,31), (9,33), (10,36), (11,42), (12,39), (13,56), (14,55), (15,63), (16,52), (17,66), (18,52), (19,80), (20,71))

def model(data: List[(Int, Int)]) = for {
    slope <- LogNormal(0,1).param
    intercept <- LogNormal(0,1).param
    regression <- Predictor.from{x: Int => Poisson(x*slope + intercept)}.fit(data)
} yield regression
```

We can fit a model to our observations, then generate predictions as before with

```
val modelNow = model(observations)
val predictionsNow = modelNow.map(_.predict(30)).sample()
```

which, under the hood, means we're running MCMC to generate a sample from the posterior distribution over the model parameters, then using those parameter values to generate predictions.

We can also record that sample from the posterior

```
val recording = modelNow.record
```

and later, given the code which defines the model, replay that sample and use it to generate predictions with

```
val modelLater = model(List())
val predictionsLaterA = modelLater.map(_.predict(30)).replay(recording)
val predictionsLaterB = modelLater.map(_.predict(21)).replay(recording)
val predictionsLaterC = modelLater.map(_.predict(35)).replay(recording)
```

The point here is that fitting to observations is what lets us correctly generate samples from the posterior, but since we already have those, we don't have to fit again, we can just plug them in and go.

**Comment by avi-stripe** [comment]
A couple of additional notes about replay/record:

- note that although we're running the model building code again, we can do it without having the original observations (`model(List())` instead of `model(observations)`)
- this is a brand new (but sorely missing) feature and we'd love feedback on how/whether it works for you and whether a different API would be better

**Comment by avi-stripe** [comment]
Oh, and pretty crucially:
* You can serialize and load the "recording"

**Comment by espears4sq** [comment]
Awesome. Thanks for this detailed response. I will take a look at some of these options coming up. I'm new to Scala and for a project I have been seeking a Scala alternative to pymc, and rainier seems to be currently the best option, despite being very young.

If there are any tasks I can do to contribute to Rainier, please let me know. I would be happy to contribute, even on small / less interesting stuff while I am ramping up with Scala.
