### ISSUE TITLE
Using rainier with spark?

### ISSUE THREAD

**Issue by nickresnick** [stripe/rainier#349]
Instead of computing the likelihood and gradient on a sequence of data points, could we do it in parallel on a spark RDD?

For example with breeze I can create a custom `DiffFunction` that works on a spark RDD and returns the aggregated loss function and gradient needed for breeze's L-BFGS routine. In pseudocode this looks like:

```
import breeze.optimize.DiffFunction
class myDiffFunction(data: RDD[Double]) extends DiffFunction {
  override def calculate(params: Seq[Double]): (Double, Seq[Double]) = {
    // compute the loss and gradient in parallel on the data RDD then sum across elements
    val lossAndGradientAtEachDataPoint = data.map { dataPoint => (someLossFunction(dataPoint), someGradientFunction(dataPoint)) }
    (lossAndGradientAtEachDataPoint.map(_._1).sum, lossAndGradientAtEachDataPoint.map(_._2).sum)
  }
}
```
I'm not as familiar with HMC or rainier, but I imagine if we're computing a likelihood and gradient at a sequence of data points and summing it, we could do the same sort of parallelized task instead?

**Comment by avibryant** [comment]
This is definitely possible in principle. The integration would be a fair amount of work: for example, Rainier compiles the model into custom JVM bytecode, and we'd need to figure out how to distribute that across the spark cluster; we'd also need to find clean way to integrate RDD-based data sources into Rainier's API. But the basic idea of computing the likelihood and gradient for each data point, and then summing those, certainly holds, and if someone wanted to take this on I'd be happy to provide guidance.

The other thing I'm not sure about, but it sounds like you might have some experience with, is how many Spark jobs it's reasonable to launch in sequence while sampling; since you'd have to launch one for every iteration, this would generally be in the 1000s. Are you already doing O(1000) sequential iterations for L-BFGS? With Hadoop MapReduce, the overhead of doing that would be high enough I probably wouldn't even try it, but I have much less operational experience with Spark and maybe it's more reasonable in that context.

**Comment by nickresnick** [comment]
So you're asking: how would overhead change if the optimization iteration count went from O(100), as is common in L-BFGS, to O(1000), as is common in MCMC sampling?

With spark, I haven't experienced the overhead increasing with iteration count. The last iteration of the optimization is usually just as fast as the first. The key with any iterative program in Spark is to cache the RDD in memory beforehand. One thing I'm actually not sure about is if Spark is smart enough to keep the same partition of data on the same executor throughout the fit to minimize overhead. Hmm. In any case, I don't think iteration count would be an issue.

Yeah, seems like it would be a lot. As far as serializing the custom bytecode, I believe the object just needs to extend java.io.Serializable for it to work with Spark. Have you ever played around with using scala's parallel collections? That's a naive proxy for what Spark could do, and would only require adding a `.par` anytime we map through the data points.

**Comment by avibryant** [comment]
I wouldn't specifically use `.par` and scala collections within the HMC iterations because we try to make the hot loop of the sampler allocation-free, but I very much do plan to support parallel likelihood computations on multi-core machines and that should be quite straightforward. (We do already use `.par`  for sampling from multiple chains in parallel).
