### ISSUE TITLE
Scala 2.13 Build

### ISSUE THREAD

**Issue by valencik** [stripe/rainier#428]
A tracking issue for creating a Scala 2.13 build.

- [x] Migrate from tut to mdoc (tut is deprecated and does not support 2.13.1)
- [ ] Upgrade cats to a version supporting 2.13
- [ ] Upgrade Evilplot to a version supporting 2.13 (https://github.com/cibotech/evilplot/issues/95)

**Comment by avibryant** [comment]
Awesome, thank you for tracking this.

Re mdoc: my plan had actually been to migrate to Jupyter notebooks using jupytext so that the notebooks were stored in markdown; this is mostly to for ease of embedding generated images. I don't see any obvious way to do that in mdoc?

Re evilplot, the reason we're on an old version is to keep 2.11 compat which AFAIK Stripe still needs (though maybe not for long? @andyscott). AFAIK there's no version that supports both 2.11 and 2.13 :/

**Comment by andyscott** [comment]
We should be able to confidently drop 2.11 support at the end of January.

I'll likely forget to circle back here with updates, so don't hesitate to ping as we track into next month.

**Comment by valencik** [comment]
Update as of 0.3 (https://github.com/stripe/rainier/pull/419), the following modules are cross published to 2.13 (as well as 2.11 and 2.12):
- `rainierBase`
- `rainierCompute`
- `rainierSampler`
- `rainierCore`

Notably `rainierNotebook` is not cross published on 2.13 as it is still blocked by Evilplot.
Happy to close this and open an issue just tracking 2.13 support on `rainierNotebook` if you'd prefer.

**Comment by avibryant** [comment]
Yes, let's close this and add a new, narrower issue.
